### ISSUE TITLE
xml_content.Sentence.get_tokens sometimes produces Exception

### ISSUE THREAD

**Issue by ffshr** [weblyzard/weblyzard_api#10]
We are getting at the moment errors on https://github.com/weblyzard/weblyzard_api/blob/master/src/weblyzard_api/xml_content/__init__.py#L134:

`ValueError: too many values to unpack`

I'm trying to find XML document that cause this error to see if it's an error in the XML (and thus somewhere during it's creation) or if it's a correct XML but the method has a bug.

**Comment by AlbertWeichselbraun** [comment]
The problem lies most probably in the token or pos tag attribute - i.e. die number of tokens is != the number of pos tags. 

I agree that identifying the document (and sentence) that causes this problem is key to dealing with it.

**Comment by ffshr** [comment]
The error is this: 
```
<wl:sentence dependency="5:Atr_M 0:AuxG 0:Atr 2:Atr 3:Atr -1:Coord 16:AuxC 8:Atr 11:Atr_M 11:AuxX 11:Sb_M 6:Coord 11:AuxG 5:NMOD 13:Atr 14:Atr 15:Atr" md5sum="02a5bf13744d2185063f69f18b3394ce" pos_tags="N Z C C N Z N A N Z N J Z N N N N" significance="45.920940706546546" token="0,3 3,45,7 8,11 12,14 15,16 17,23 24,34 35,45 45,46 47,53 54,55 55,56 57,61 62,67 68,73 74,96">
```
notice the delimiters for the second token, it is 3,45,7. In fact it should be 3,4 and 5,7 - somewhere the space got lost.
```
token="0,3 3,45,7 8,11 12,14 15,16 17,23 24,34 35,45 45,46 47,53 54,55 55,56 57,61 62,67 68,73 74,96"
```
This obviously results in an error during unpacking.

**Comment by ffshr** [comment]
closing issue here, since it's not a bug in this project but somewhere else.
