### ISSUE TITLE
Java Code

### ISSUE THREAD

**Issue by wolferl42195** [weblyzard/weblyzard_api#128]
I tried to check out the Java version with eclipse but it did not compile because there are some issues with constructors. Is the current version stable?

**Comment by AlbertWeichselbraun** [comment]
Hi,

We use the Travis ci for continuous integration which is able to build the code (see README.md).

Can you please check your setup (Please note that we require Java 10 for the API to build).

Cheers,
  Albert :-)

**Comment by wolferl42195** [comment]
Thanks for the fast response. I check the travis plugin for eclipse. :-) Hope it works

**Comment by AlbertWeichselbraun** [comment]
Did you install lombok for your IDE?
  https://projectlombok.org/setup/eclipse

You won't need it, if you build the project with travis or maven (which automatically fetch it), but it is required to build it within the IDE.

**Comment by wolferl42195** [comment]
I use maven and after installing Lombok it compiled without any problems. I run also some unit tests successfully. Now I will try to get familiar with the API. Thanks
