### ISSUE TITLE
Use assumptions for unit tests that require server components

### ISSUE THREAD

**Issue by AlbertWeichselbraun** [weblyzard/weblyzard_api#35]
Currently java unit tests that rely on a server component fail, if the server is not present.
I would rather like to suggest
1. using JUnit's `Assume` to skip these tests (see http://eclipsesource.com/blogs/2009/10/07/using-junits-assume-for-faster-tests/)
2. and logging an appropriate message

**Comment by normansuesstrunk** [comment]
@rodmaykel: i removed the skipTests configuration from the pom.xml since we handle the check for the running service while unit testing in the unit tests itself.

**Comment by normansuesstrunk** [comment]
@AlbertWeichselbraun: I think we can close this issue

**Comment by AlbertWeichselbraun** [comment]
that's good - please make it so :)
