### ISSUE TITLE
evaluate solutions for deploying javadoc

### ISSUE THREAD

**Issue by normansuesstrunk** [weblyzard/weblyzard_api#36]
* docs for python use readthedocs.io
* search for a similar solution for the javadocs

**Comment by normansuesstrunk** [comment]
Possible solutions: 
* http://javadoc.io/
* https://vaadin.com/blog/-/blogs/host-your-javadoc-s-online-in-github

When the project is released on maven central, the javadoc is automatically available throught the javadoc.io project: http://javadoc.io/doc/com.weblyzard.api/weblyzard-api/0.0.5

@AlbertWeichselbraun: I added this link to the Readme.md and I think this is a good solution (?)

**Comment by AlbertWeichselbraun** [comment]
very nice :)
