### ISSUE TITLE
Implement Jairo client

### ISSUE THREAD

**Issue by AlbertWeichselbraun** [weblyzard/weblyzard_api#39]

**Comment by normansuesstrunk** [comment]
see commit https://github.com/weblyzard/weblyzard_api/commit/cb07ae590ddb81b5fcab455700015098394daf36 and https://github.com/weblyzard/weblyzard_api/commit/c1bbf2bbdd86aff6f25962e0e36609790d9b6df7

**Comment by normansuesstrunk** [comment]
client will be improved after further error handling in the jairo service is implemented (https://gitlab.semanticlab.net/core/jairo/issues/11)
