### ISSUE TITLE
add internal build target

### ISSUE THREAD

**Issue by AlbertWeichselbraun** [weblyzard/weblyzard_api#40]
Currently we can only build and publish the weblyzard_api over jenkins to mavencentral.
=> offer two build options

1. to mavencentral (stable releases) with the -SNAPSHOT extension (default)
2. to internal repository (develop-java) with the -SNAPSHOT extension

@rodmaykel may i ask you to adjust the build script for the stable release to automatically remove the -SNAPSHOT extension from the version number (analogous to the removal of `-dev` for python based packages).

**Comment by normansuesstrunk** [comment]
i added 2 deployment profiles to the pom.xml that enables to run 2 deployments: 

```
mvn deploy -Denvironment=semanticlab
```
Deploys to the private semanticlab maven repo

```
mvn deploy -Denvironment=mavencentral
```
deploys to maven central

it would also be possible to add the version propertie to the profiles to leave / leave out the **-SNAPSHOT** ? 

I documented the deployment also in the README.md

**Comment by AlbertWeichselbraun** [comment]
hoi norman 

that's excellent - would it be possible to do the semanticlab build per default?

may I suggest leaving the -SNAPSHOT suffix in the pom.xml. @rodmaykel can then configure jenkins to remove it for the mavencentral builds (analogous to the python builds).

cheers,
  albert :-)

**Comment by normansuesstrunk** [comment]
```
would it be possible to do the semanticlab build per default?
```
it is already. when you run 
```
mvn deploy
```
it will be deployed to semanticlab 

se the <activeByDefault> tag in the pom.xml
```
<activation>
				<activeByDefault>true</activeByDefault>
				<property>
					<name>environment</name>
					<value>semanticlab</value>
				</property>
			</activation>
```

**Comment by AlbertWeichselbraun** [comment]
that's excellent - from my point of view we can close this issue.

p.s. @normansuesstrunk  - please add yourself to the list of contributors at the pom.xml.

**Comment by normansuesstrunk** [comment]
```
please add yourself to the list of contributors at the pom.xml.
```
done. closing the issue

**Comment by rodmaykel** [comment]
@AlbertWeichselbraun, I will configure jenkins to remove the -SNAPSHOT tag...
Cheers!
