### ISSUE TITLE
usefulness of nonPreemtive auth strategy.

### ISSUE THREAD

**Issue by PhilippKuntschik** [weblyzard/weblyzard_api#56]
using the nonPreemtive Basic Auth strategy leads to every call sent twice to webservices with authentication. Although this is not a problem with small amounts of calls, it is a huge performance issue with >100K documents. I experienced a performance boost by 100% when removing the nonPreemtive strategy setting (67s/1000Calls ==> 33s/1000Calls) .

https://github.com/weblyzard/weblyzard_api/blob/master/src/java/main/com/weblyzard/api/client/BasicClient.java#L77-L80

I would like to ask you for your mind on the following three options that I see:
a) stick with the nonPreemtive setting. In terms of Information Security, this is the best approach, as it does only use the authentication header if really needed.
b) remove the nonPreemtive setting. This would be the most intuitive and direct way to speed things up.
c) make nonPreemtive optional via an environment variable, set default to option a)

@AlbertWeichselbraun @normansuesstrunk

**Comment by AlbertWeichselbraun** [comment]
i think we should just use preemptive auth:

- for this to be a problem you would need to connect to a hostile server.
- if the server is hostile (i.e. wants to spoof your credentials) it is
very likely that the system will set the auth header which would lead to
the login info being sent anyways.

just a final note - the numbers you send us indicate that processing
time is not an issue for this web service but rather the number of
available connects.

**Comment by PhilippKuntschik** [comment]
albert,

you are right, this could be an issue with the connection as well. I researched a bit and it seems that we, indeed create a new client for every call, hence the authentication requests:

[Webtarget.path(String) : Create a new WebTarget instance by appending path to the URI of the current target instance. ](https://jersey.java.net/apidocs/2.22/jersey/javax/ws/rs/client/WebTarget.html#path(java.lang.String))
https://github.com/weblyzard/weblyzard_api/blob/master/src/java/main/com/weblyzard/api/client/RecognyzeClient.java#L68-L69

We should add some kind of connection storage to the BasicClient that enables reusing an old connection.

**Comment by PhilippKuntschik** [comment]
dear albert,

I have restructured the Client to re-use as much as possible:
https://github.com/weblyzard/weblyzard_api/commit/c749dfab3d468ddb59635a14ec817ad8b5bc51c4

But still, connections to secured webservices always end up in two separate call, the first being revoked with a 401 HTTP result, while the second one contains the authentication header. You can reproduce this behaviour with [JeremiaClientTest](https://github.com/weblyzard/weblyzard_api/blob/issue/%2356/src/java/test/com/weblyzard/api/client/JeremiaClientTest.java) and env WEBLYZARD_API_DEBUG set to true.

As I am unsure how to proceed, I would like to ask, what the expected behaviour would look like:
a) should the server recognize that the client/ the connection is already authorized and not send an 401
b) should the client recognize that this connection needs to have the authorization header set every time and behave like this?
c) should the server respond with a token that has to be sent with every further request?

I have checked in which way Chrome browser behaves, it does send the Authorization header every time. As today I assume therefore that b) would be correct, but as I said, I am not sure if it is correct and where to fix this.

Cheers,
Philipp

**Comment by AlbertWeichselbraun** [comment]
dear phil,

exactly - b) is the way to go. with basic http auth the client sends the
credentials with every requests.

cheers,
  albert :-)	

--

**Comment by PhilippKuntschik** [comment]
dear albert,

I am afraid to say that I am not able to find a solution.. It already seems that this behaviour is "as designed" in Jersey:

> BASIC NON-PREEMPTIVE: Basic non-preemptive authentication. In non-preemptive mode the authentication information ** is added only when server refuses the request with 401 status code and then the request is repeated ** with authentication information. This mode has negative impact on the performance. The advantage is that it does not send credentials when they are not needed. This mode must be combined with usage of SSL/TLS as the password is send only BASE64 encoded.

I suspect that this is for each request and not only for new WebTargets/Clients. Did we ever use this feature as expected?

cheers, 
Philipp

**Comment by PhilippKuntschik** [comment]
nonPreemtive was removed.
