### ISSUE TITLE
missing sentence

### ISSUE THREAD

**Issue by vendi12** [weblyzard/weblyzard_api#7]
one of the sentences is dropped by the XMLContent parser (unittest TBA)

**Comment by AlbertWeichselbraun** [comment]
can you please provide an example query which triggers this bug?

**Comment by vendi12** [comment]
Im preparing a unit test ATM, will add it to  weblyzard_api/src/weblyzard_api/xml_content/parsers/xml_2013.py
in a separate bug-branch, ok?

**Comment by AlbertWeichselbraun** [comment]
that's okay - please assign the bug to heinz/max, if its a weblyzard api problem and not a problem of jeremia.

**Comment by vendi12** [comment]
done, is it a feature or a bug that the sentences with the same md5sum are returned just once?

**Comment by vendi12** [comment]
meaning that they are returned everytime from Jeremia, but then get deduplicated with the XMLContent parser. It is not intuitive to expect those gaps.

**Comment by langatium** [comment]
XMLContent has now a new parameter `remove_duplicates`. Per default it's `true`. But if set to `false` it will also return double sentences. Made changes to xml_content, parsers and created a new version.
