### ISSUE TITLE
XMLContent - Documentation

### ISSUE THREAD

**Issue by langatium** [weblyzard/weblyzard_api#8]
Dear all, 

as far as I know we had a documentation about the XML format somewhere in GDrive. I think it would be the best, if we move this documentation directly to the module `weblyzard_api.xml_content`. 

What do you think? 

Could someone, who knows where the docu lives, add it to the module?

thanks :)

**Comment by AlbertWeichselbraun** [comment]
hi heinz

we have already integrated the documentation in
  http://weblyzard-api.readthedocs.org/en/latest/weblyzard_api.data_format.xml_format.html

cheers,
  albert :)
